version: '3'
services:
  mypostgres:
    image: postgres
    ports:
      # databaze bude bezet na portu 5555
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - mypostgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.cz
      PGADMIN_DEFAULT_PASSWORD: admin
